version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.25.0
    - 8.26.1
    - 8.28.1
    - 8.29.0
    - 8.30.1
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: spatie/data-transfer-object
    versions:
    - 2.8.0
    - 2.8.1
    - 2.8.2
    - 2.8.3
    - 3.0.0
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
  - dependency-name: barryvdh/laravel-ide-helper
    versions:
    - 2.10.0
    - 2.9.0
    - 2.9.1
    - 2.9.2
    - 2.9.3
  - dependency-name: nunomaduro/collision
    versions:
    - 5.4.0
  - dependency-name: orchestra/testbench
    versions:
    - 6.12.1
    - 6.14.0
    - 6.15.0
    - 6.16.0
    - 6.17.0
    - 6.9.0
  - dependency-name: laravel/horizon
    versions:
    - 5.6.5
    - 5.7.0
    - 5.7.1
    - 5.7.2
    - 5.7.3
    - 5.7.4
    - 5.7.5
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.3
    - 9.5.4
  - dependency-name: itsgoingd/clockwork
    versions:
    - 5.0.7
