<?php


namespace Seatplus\Eveapi\Models\Killmails;


use Illuminate\Database\Eloquent\Model;
use Seatplus\Eveapi\Models\Universe\Type;

class KillmailItem extends Model
{

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['has_content'];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    public function getHasContentAttribute()
    {
        return $this->content()->exists();
    }

    public function content()
    {
        return $this->hasMany(self::class, 'location_id', 'id');
    }

    public function type()
    {
        return $this->hasOne(Type::class, 'type_id', 'type_id');
    }

    public function delete()
    {

        $this->content()->delete();

        return parent::delete(); // TODO: Change the autogenerated stub
    }

}