name: Webhook Post Action

on:
  release:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Webhook POST Action
      uses: muinmomin/webhook-action@v1.0.0
      with:
        # URL of webhook to send post request to
        url: ${{ secrets.WEBHOOK_URL }}
        # JSON string of data to pass into request
        #data: {} # optional, default is {}
