name: Laravel

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  laravel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      uses: php-actions/composer@v5
      with:
        args: --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: '7.4'
        extensions: mbstring, dom, fileinfo
        coverage: xdebug #optional
    - name: Redis Server in GitHub Actions
      uses: supercharge/redis-github-action@1.1.0
      with:
        # Redis version to use
        redis-version: 5 # optional, default is latest
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: afe50b57038790ac97669452ea4967d142354893104f32a33fdc54de112dc1d1
        COMPOSER_ROOT_VERSION: dev-develop
      with:
        coverageCommand: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
        debug: false
