name: Tests

on:
  push:
    branches: [ 3.x, 4.x ]
  pull_request:
    branches: [ 3.x, 4.x ]

jobs:
  ci:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres # required for the default postgres image but not needed if connected from localhost
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
      mariadb:
        image: mariadb:10.7
        env:
          MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
          MARIADB_DATABASE: laravel
          MARIADB_USER: root
          MARIADB_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: '8.3'
        extensions: mbstring, dom, fileinfo
        coverage: xdebug #optional
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: afe50b57038790ac97669452ea4967d142354893104f32a33fdc54de112dc1d1
        COMPOSER_ROOT_VERSION: dev-develop
      with:
        coverageCommand: vendor/bin/pest --coverage --ci
        debug: false
